version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"

  go-consumer:
    build:
      context: ./consumer
    depends_on:
      - zookeeper
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
    command: ["./consumer"]

  app:
    build:
      context: ./app
#    image: log-generator:v0.1         # Use the locally built image
    container_name: loggen-my
    volumes:
      - shared-log:/root/app  # Mount the shared named volume
    depends_on:
      - aggregator

  aggregator:
    build:
      context: ./aggregator
    container_name: aggregator
    environment:
      - KAFKA_BROKER=kafka:9092
    platform: linux/amd64
    volumes:
      - shared-log:/app                    # Mount the shared named volume
      - ./aggregator/fluent.conf:/aggregator/etc/fluent.conf  # Fluentd configuration
    command: ["fluentd", "-c", "/aggregator/etc/fluent.conf", "-vv"]
    depends_on:
      - kafka

volumes:
  shared-log:  # Define the shared named volume